### THRESHOLDS (FROM ALL 3 CODERS) ###

# timing
SAMPLE_INTERVAL = 1.0
AVG_WINDOW_MIN = 5

# noises for display
OUTSIDE_MIN_DB = 7
OUTSIDE_MAX_DB = 120
INSIDE_MIN_DB = 7
INSIDE_MAX_DB = 45

# alarm settings
ALARM_THRESHOLD_DB = 55
ALARM_RESET_DB = 52
ALARM_COOLDOWN_SEC = 5
